# Generated by Django 4.2.3 on 2023-07-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="title",
            field=models.CharField(max_length=60, null=True),
        ),
    ]
