# Generated by Django 4.2.3 on 2023-07-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_file_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="audio/%Y/%m/%d/"),
        ),
    ]
