# Generated by Django 4.2.3 on 2023-07-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_file_audio_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="file",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterField(
            model_name="file",
            name="audio_file",
            field=models.FileField(upload_to="audio_files"),
        ),
    ]
